apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-redis
spec:
  selector:
    matchLabels:
      app: boot-redis
  replicas: 2
  template:
    metadata:
      labels:
        app: boot-redis
    spec:
      containers:
      - name: boot-redis
        image: pseudojo/spring-boot-redis-docker
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz-seoul
        - name: config
          mountPath: /application.yml
          subPath: application.yml
          readOnly: true
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
        name: tz-seoul
      - name: config
        secret:
         secretName: boot-redis-config
         defaultMode: 0440
---
apiVersion: v1
kind: Service
metadata:
  name: boot-redis
  labels:
    app: boot-redis
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: boot-redis
---

