apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-mysql
spec:
  selector:
    matchLabels:
      app: boot-mysql
  replicas: 2
  template:
    metadata:
      labels:
        app: boot-mysql
    spec:
      containers:
      - name: boot-mysql
        image: pseudojo/spring-boot-mysql-docker:11-jdk
        env:
        - name: DATABASE_HOST
          value: mysql.tenant-dev
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_NAME
          value: demotest
        - name: DATABASE_USER
          value: root
        - name: DATABASE_PASSWORD
          value: 'qwer1234!@#$'
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz-seoul
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
        name: tz-seoul
---
apiVersion: v1
kind: Service
metadata:
  name: boot-mysql
  labels:
    app: boot-mysql
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: boot-mysql
---

